"""add source_chunk_ids to messages

Revision ID: 1e10fd8521a7
Revises: 7fa9ae014d2e
Create Date: 2026-09-09 14:44:13.591813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e10fd8521a7'
down_revision: Union[str, None] = '7fa9ae014d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('source_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'source_chunk_ids')
    # ### end Alembic commands ###
